[package]
name = "lambda"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
tokio = { version = "0.2.0-alpha.5" }
hyper = { version = "0.13.0-alpha.2", features = ["unstable-stream"] }
async-stream = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.39"
fehler = "1.0.0-alpha.1"
bytes = "0.4"
http = "0.1.17"
headers = "0.2.1"
lazy_static = "1.3.0"
proptest = { git = "https://github.com/davidbarsky/proptest" }
proptest-attributes = { git = "https://github.com/davidbarsky/proptest" }
lambda-attributes = { path = "../lambda-attributes", version = "0.1.0" }

[dev-dependencies]
trybuild = "1"
